import json

def list_CompTerit():
    return [
		'ABBEVILLE',
		'AGEN',
		'AIX-EN-PROVENCE',
		'AJACCIO',
		'ALBERTVILLE',
		'ALBI',
		'ALENÇON',
		'ALTKIRCH',
		'ALÈS',
		'AMBERT',
		'AMIENS',
		'ANGERS',
		'ANGOULÊME',
		'ANNECY',
		'ANNEMASSE',
		'ANTIBES',
		'ANTONY',
		'ARBOIS',
		'ARGENTAN',
		'ARLES',
		'ARRAS',
		'AUBAGNE',
		'AUBUSSON',
		'AUCH',
		'AURAY',
		'AURILLAC',
		'AUXERRE',
		'AVALLON',
		'AVESNES-SUR-HELPE',
		'BAR-LE-DUC',
		'BASTIA',
		'BAYEUX',
		'BAYONNE',
		'BEAUNE',
		'BEAUVAIS',
		'BELFORT',
		'BELLAC',
		'BELLEY',
		'BERGERAC',
		'BERNAY',
		'BESANÇON',
		'BIARRITZ',
		'BLAYE',
		'BLOIS',
		'BOBIGNY',
		'BOISSY-SAINT-LÉGER',
		'BONNEVILLE',
		'BORDEAUX',
		'BOURG-EN-BRESSE',
		'BOURGANEUF',
		'BOURGES',
		'BOURGOIN-JALLIEU',
		'BRESSUIRE',
		'BREST',
		'BRIANÇON',
		'BRIGNOLES',
		'BRIOUDE',
		'BRIVE-LA-GAILLARDE',
		'BÉTHUNE',
		'BÉZIERS',
		'CAEN',
		'CAHORS',
		'CAMBRAI',
		'CANNES',
		'CARCASSONNE',
		'CARPENTRAS',
		'CARVIN',
		'CASTELNAUDARY',
		'CASTELSARRASIN',
		'CASTRES',
		'CAYENNE',
		'CHALON-SUR-SAÔNE',
		'CHAMBÉRY',
		'CHARENTON-LE-PONT',
		'CHARLEVILLE-MÉZIÈRES',
		'CHAROLLES',
		'CHARTRES',
		'CHAUMONT',
		'CHERBOURG',
		'CHINON',
		'CHOLET',
		'CHÂLONS-EN-CHAMPAGNE',
		'CHÂTEAUBRIANT',
		'CHÂTEAUDUN',
		'CHÂTEAULIN',
		'CHÂTILLON-SUR-SEINE',
		'CIVRAY',
		'CLERMONT',
		'CLERMONT-FERRAND',
		'COGNAC',
		'COLMAR',
		'COMPIÈGNE',
		'CONDOM',
		'CORTE',
		'COULOMMIERS',
		'COUTANCES',
		'CRÉTEIL',
		'CUSSET',
		'CÉRET',
		'DAX',
		'DIE',
		'DIGNE-LES-BAINS',
		'DIJON',
		'DINAN',
		'DOLE',
		'DOMFRONT',
		'DOUAI',
		'DOULLENS',
		'DRAGUIGNAN',
		'DREUX',
		'DUNKERQUE',
		'ECOUEN',
		'ELBEUF',
		'EPERNAY',
		'EPINAL',
		'ESPALION',
		'EVREUX',
		'EVRY',
		'FALAISE',
		'FIGEAC',
		'FLORAC',
		'FOIX',
		'FONTAINEBLEAU',
		'FORBACH',
		'FORT DE FRANCE',
		'FRÉJUS',
		'GANNAT',
		'GAP',
		'GONESSE',
		'GOURDON',
		'GRASSE',
		'GRAY',
		'GRENOBLE',
		'GUÉRET',
		'HOUDAIN',
		'HUNINGUE',
		'HYÈRES',
		'ISSOIRE',
		'IVRY-SUR-SEINE',
		'JONZAC',
		'LA MURE',
		'LA ROCHE-SUR-YON',
		'LA ROCHELLE',
		'LANGRES',
		'LAON',
		'LARGENTIÈRE',
		'LAVAL',
		'LAVAUR',
		'LE HAVRE',
		'LE MANS',
		'LE PUY-EN-VELAY',
		'LECTOURE',
		'LENS',
		'LES ANDELYS',
		"LES SABLES-D'OLONNE",
		'LIBOURNE',
		'LILLE',
		'LIMOGES',
		'LIMOUX',
		'LISIEUX',
		'LOCHES',
		'LODÈVE',
		'LONS-LE-SAUNIER',
		'LORIENT',
		'LOUDÉAC',
		'LOURDES',
		'LOUVIERS',
		'LUNÉVILLE',
		'LURE',
		'LYON',
		'MAMERS',
		'MAMOUDZOU',
		'MANOSQUE',
		'MANTES-LA-JOLIE',
		'MARENNES',
		'MARMANDE',
		'MARSEILLE',
		'MARTIGUES',
		'MARVEJOLS',
		'MAUBEUGE',
		'MAURIAC',
		'MAYENNE',
		'MEAUX',
		'MELLE',
		'MELUN',
		'MENDE',
		'MENTON',
		'METZ',
		'MILLAU',
		'MIRANDE',
		'MOISSAC',
		'MOLSHEIM',
		'MONT-DE-MARSAN',
		'MONTARGIS',
		'MONTAUBAN',
		'MONTBRISON',
		'MONTBÉLIARD',
		'MONTDIDIER',
		'MONTLUÇON',
		'MONTMORENCY',
		'MONTPELLIER',
		'MOULINS',
		'MOÛTIERS',
		'MULHOUSE',
		'MURAT',
		'MURET',
		'MÂCON',
		'NANCY',
		'NANTERRE',
		'NANTES',
		'NANTUA',
		'NARBONNE',
		'NEVERS',
		'NICE',
		'NIORT',
		'NOGENT-LE-ROTROU',
		'NONTRON',
		'NOUMEA',
		'NYONS',
		'NÉRAC',
		'NÎMES',
		'ORANGE',
		'ORLÉANS',
		'ORTHEZ',
		'PAIMBOEUF',
		'PARIS',
		'PARTHENAY',
		'PAU',
		'PERPIGNAN',
		'PITHIVIERS',
		'PLOËRMEL',
		'POINTE A PITRE',
		'POISSY',
		'POITIERS',
		'PONTARLIER',
		'PONTIVY',
		'PONTOISE',
		'PRADES',
		'PRIVAS',
		'PROVINS',
		'PÉRIGUEUX',
		'PÉRONNE',
		'QUIMPER',
		'QUIMPERLÉ',
		'RAMBOUILLET',
		'REDON',
		'REIMS',
		'RENNES',
		'RIBÉRAC',
		'ROANNE',
		'ROCHEFORT',
		'RODEZ',
		'ROUBAIX',
		'ROUEN',
		'SAINT DENIS DE LA REUNION',
		'SAINT-BRIEUC',
		'SAINT-DENIS',
		'SAINT-DIÉ',
		'SAINT-ETIENNE',
		'SAINT-GAUDENS',
		'SAINT-GERMAIN-EN-LAYE',
		'SAINT-MALO',
		'SAINT-NAZAIRE',
		'SAINT-OMER',
		'SAINT-QUENTIN',
		'SAINTES',
		'SALON-DE-PROVENCE',
		'SANNOIS',
		'SARLAT',
		'SARREGUEMINES',
		'SARTÈNE',
		'SAUMUR',
		'SAVERNE',
		'SEDAN',
		'SEGRÉ',
		'SEMUR-EN-AUXOIS',
		'SENLIS',
		'SENS',
		'SOISSONS',
		'STRASBOURG',
		'SÈTE',
		'TARASCON',
		'TARBES',
		'THANN',
		'THIERS',
		'THONON-LES-BAINS',
		'TONNERRE',
		'TOUL',
		'TOULON',
		'TOULOUSE',
		'TOURCOING',
		'TOURS',
		'TROYES',
		'TRÉVOUX',
		'TULLE',
		'USSEL',
		'VALENCE',
		'VALENCIENNES',
		'VALOGNES',
		'VANNES',
		'VENDÔME',
		'VERDUN',
		'VERSAILLES',
		'VERVINS',
		'VESOUL',
		'VICHY',
		'VIENNE',
		'VILLEFRANCHE-DE-LAURAGAIS',
		'VILLEFRANCHE-SUR-SAÔNE',
		'VILLEURBANNE',
		'VIRE',
		'YSSINGEAUX',
		'YVETOT'
    ]

def list_Spe():
    return [
		'Auto (Code de la route)',
		 'Auto (Vente/Réparation)',
		 'Corporel',
		 'Droit bancaire et financier',
		 'Droit commercial',
		 "Droit de l'environnement",
		 'Droit de la consommation',
		 'Droit de la construction',
		 'Droit de la famille',
		 'Droit de la fiducie, du patrimoine',
		 'Droit de la responsabilité',
		 'Droit des assurances',
		 "Droit des baux d'habitation",
		 'Droit des biens',
		 'Droit des personnes',
		 'Droit des transports',
		 'Droit fiscal',
		 'Droit immobilier',
		 'Droit international/communautaire',
		 'Droit médical',
		 'Droit notarial',
		 'Droit public',
		 'Droit pénal',
		 'Droit rural',
		 'Droit social',
		 'Nouvelles technologies',
		 "Voies d'exécution"
    ]
	
	
def list_domaines():
    return [
		'Affaires',
		'Automobile',
		'Autres services',
		'Banques assurances finances',
		'Biens mobiliers et dommages mobiliers',
		'Client bailleur',
		'Copropriété',
		'Environnement',
		'Famille',
		'Fiscal',
		'Internet-téléphonie',
		'Locaux professionnels',
		'Logement - Habitat',
		'Multipropriété, SCI, indivision',
		'Procédures et autres Droits (IJ)',
		'Protection sociale, prévoyance, retraite',
		'Public',
		'Pénal et disciplinaire',
		'Recours contre un organisme social',
		'Recours corporels contractuels',
		'Recours corporels délictuels',
		'Relations commerciales',
		'Successions - Libéralités - Donations',
		'Travail',
		'Travaux',
		'Vie associative (constitution, AG, liquidation)',
		'Voisinage',
		'indéfini'
    ]